drivers: imx_wdog: fix compilation watchdog driver on mx7ulp
Define WDOG_BASE and WDOG_SIZE value for mx7ulp platform.

$ make PLATFORM=imx-mx7ulpevk CFG_DT=n
core/drivers/imx_wdog.c:151:42: error: WDOG_BASE undeclared here (not in a function); did you mean WDOG_CS?
151 | register_phys_mem_pgdir(MEM_AREA_IO_SEC, WDOG_BASE, CORE_MMU_PGDIR_SIZE);
    |

Signed-off-by: Clement Faure <clement.faure@nxp.com>
Acked-by: Jerome Forissier <jerome@forissier.org>
(cherry picked from commit c54ad22aaecb6c52bdb8abb41cd0b11279f6fecd)
(cherry picked from commit 56645351ef7225c9032fb7886b6ce4b5b2361b28)