LFOPTEE-211 core: update tee_entry_is_sdp_cached
Take in consideration change introduce by
commit 8afe7a7c5220
("core: rename mobj_get_cattr() to mobj_get_mem_type()")
and
commit 8b427282e747
("core: change TEE_MATTR_CACHE_ to TEE_MATTR_MEM_TYPE_")

to the fix following build errors
core/tee/entry_std.c: In function 'tee_entry_is_sdp_cached':
core/tee/entry_std.c:595:14: error: implicit declaration of function
'mobj_get_cattr'; did you mean 'mobj_get_pa'?
[-Werror=implicit-function-declaration]
  595 |         if (!mobj_get_cattr(*sdp_mem_mobjs, &cattr))
      |              ^~~~~~~~~~~~~~
      |              mobj_get_pa
core/tee/entry_std.c:596:32: error: 'TEE_MATTR_CACHE_CACHED' undeclared
(first use in this function); did you mean 'TEE_MATTR_MEM_TYPE_CACHED'?
  596 |                 return cattr & TEE_MATTR_CACHE_CACHED;
      |                                ^~~~~~~~~~~~~~~~~~~~~~
      |                                TEE_MATTR_MEM_TYPE_CACHED

Fixes: 717c024a8d7e ("TEE-526 core: arm: retrieve SDP Memory cacheability")
Signed-off-by: Olivier Masse <olivier.masse@nxp.com>